### ISSUE TITLE
custom element doesn't exist: button-card (Home Assistant 0.85.0) 

### ISSUE THREAD

**Issue by sandro-defender** [kuuji/button-card#43]
after updating to 0.85.0 my lovelace not working :(
![00001](https://user-images.githubusercontent.com/26311682/51081884-a0702680-1714-11e9-8126-aef470705b46.jpg)
[Home Assistant.pdf](https://github.com/ciotlosm/custom-lovelace/files/2752823/Home.Assistant.pdf)

**Comment by brianhanifin** [comment]
I had the same thing after I upgraded to 0.85.1. It worked for a while, then even though I hadn't changed anything related to my lovelace files it broke after a few refreshes (probably a hard refresh as well). I fixed it by downgrading back to 0.85.0.

**Comment by kuuji** [comment]
I think it has nothing to do with 0.85 but has to do with the cdn I used for the lit-element library.

I tried to look into including that in the code this weekend but it's a pita. The proper solution would be to move off lit-element but that's a bigger project that I don't have time to tackle these days.

**Comment by PeteCondliffe** [comment]
> I think it has nothing to do with 0.85

I haven't done the 0.85 update yet. I'm on 84.6 and  can confirm I have the same issue

**Comment by VDRainer** [comment]
Maybe this helps?
https://discordapp.com/channels/330944238910963714/460846676358332417/534523831935827979

**Comment by gmschade** [comment]
had the same problem, changed import address on line 3 to:
https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module

**Comment by romquenin** [comment]
> had the same problem, changed import address on line 3 to:
> https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module
> 
> fixed it for me

Hello, can you please explain how did you solve it.

Thanks.

**Comment by dvd77** [comment]
> had the same problem, changed import address on line 3 to:
> https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module
> 
> fixed it for me

This doesnt work for me ! I already had that line in the button-card.js

The UI is refreshing and every few seconds its displayed ok, then it shows the error message again.. this is repeating

**Comment by gregcsw** [comment]
> > had the same problem, changed import address on line 3 to:
> > https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module
> > fixed it for me
> 
> This doesnt work for me ! I already had that line in the button-card.js
> 
> The UI is refreshing and every few seconds its displayed ok, then it shows the error message again.. this is repeating

Did you clear your cache?

**Comment by Lopton** [comment]
I will confirm that @gmschade change did fix it for me, but clearing the cache for the asynch files some times can be stubborn, so it took a minute.

**Comment by kuuji** [comment]
I'll add that to a release today. As well as the pending PR.

Thanks @gmschade

**Comment by thib5** [comment]
@kuuji  When you will update it could you add the long press support that Mat Emerson Commit ?

**Comment by IIIdefconIII** [comment]
im on the same page with this, wait for pr :) thanks dev! for making this awesome card and update it when need!

**Comment by kuuji** [comment]
@thib5 I'd rather wait for him to get it to work properly with services. 

If we release it and people start using it it'll be harder to make design changes.

**Comment by IIIdefconIII** [comment]
i did a PR to change the url:
https://github.com/kuuji/button-card/compare/master...IIIdefconIII:patch-1

**Comment by sandro-defender** [comment]
same problem again, did't fix for me :( does it help anyone ?

**Comment by IIIdefconIII** [comment]
Yeahbutton card deels to work after changing the lit url

**Comment by jonostanck** [comment]
> same problem again, did't fix for me :( does it help anyone ?

First load is unfortunately with the error but if I refresh it shows the card as it should be. So I guess changing LIT url is not the perfect cure for this issue...

**Comment by scstraus** [comment]
I'm also having this problem.  It just started disapperaing with no config change. 

I tried changing the link as described above the first time it didn’t change anything. I tried to clone it again from github and edit it again, and change that URL. I cleared my cache and rebooted my Pi, didn't work.  Then I put the old button card back (same one I had when this whole mess started), then it worked again for one night but in the morning it was broken again. 

Is there any way to just include those dependencies from the link directly into the card? I've had this happen 7-8 times with this card over the last couple months.. I love the card but I'm tired of losing it every few weeks.

**Comment by kuuji** [comment]
> I'm also having this problem. It just started disappearing with no config change. I'm on .84.6
> 
> I tried changing the link as described above the first time it didn’t change anything. I tried to clone it again from github and edit it again, and change that URL. I cleared my cache and rebooted my Pi, didn't work. Then I put the old button card back (same one I had when this whole mess started), then it worked again for one night but in the morning it was broken again.
> 
> Is there any way to just include those dependencies from the link directly into the card? I've had this happen 7-8 times with this card over the last couple months.. I love the card but I'm tired of losing it every few weeks.

Unfortunately, I can't do that. I looked into it this weekend and these depend on other stuff which also depend on other stuff and that'll be a massive mess to include all of that in the project. 

The real solution is to move away from lit-element, and I don't have the time to tackle that these days.

**Comment by gmschade** [comment]
> > I'm also having this problem. It just started disappearing with no config change. I'm on .84.6
> 
> Unfortunately, I can't do that. I looked into it this weekend and these depend on other stuff which also depend on other stuff and that'll be a massive mess to include all of that in the project.
> 
> The real solution is to move away from lit-element, and I don't have the time to tackle that these days.

I have it working with all self hosted, it's ugly and big (2M) but it is working. I will try to get it on github later today. I still have to figure out all of the git stuff :)

**Comment by scstraus** [comment]
2M is a minuscule price to pay to end this pesky problem!! Thanks!  You can put it anywhere if github is a hassle.

**Comment by kuuji** [comment]
Yeah @gmschade just send it to me on gitter. I'll take care of releasing it.

**Comment by gmschade** [comment]
Sorry, having a hard time with figureing out how to upload files on gitter
1. unzip button-card-depends.zip in the www folder
2. change import to /local/button-card-depends/@polymer/lit-element/lit-element.js
[button-card-depends.zip](https://github.com/kuuji/button-card/files/2766067/button-card-depends.zip)

**Comment by kuuji** [comment]
heh that works. Thanks @gmschade

**Comment by gmschade** [comment]
> Thanks so much @gmschade!
> 
> Just to make sure, we still need the ?module afterwards like so?
> 
> ```
> import {
>   LitElement, html,
> } from '/local/button-card-depends/@polymer/lit-element/lit-element.js?module';
> ```
> 
> EDIT: it looks like the above must be correct because it fixed all my problems immediately!! Thanks so much!

I don't really know what the '?module' does. I don't have it, but if it works for you... Was afraid I would get into whack-a-mole with the cdn problem.

> heh that works. Thanks @gmschade

Of course, and thank you @kuuji

**Comment by DavidFW1960** [comment]
Is this going to be merged today along with @bramkragten PR to fix the edit problem?
Thanks as well @kuuji

**Comment by DavidFW1960** [comment]
Just further to this, my dark-sky card stopped working today as well after updating to 0.86.0b0 but I think that's a coincidence. Replacing the local lit as per gmshade also fixed that so I edited the files in the zip file to use a /local/local-lit folder so as not to make it custom for just the button card and changed the button-card and dark-sky card .js files to point there and it all works.

**Comment by gmschade** [comment]
> Just further to this, my dark-sky card stopped working today as well after updating to 0.86.0b0 but I think that's a coincidence. Replacing the local lit as per gmshade also fixed that so I edited the files in the zip file to use a /local/local-lit folder so as not to make it custom for just the button card and changed the button-card and dark-sky card .js files to point there and it all works.

ha @DavidFW1960 that pretty much all I did, I downloaded the 0.5.2 lit_element package from npm. spent a little bit bashing out the import issues using atom's "find in project" and the console inspector in chrome.
I kinda felt like it was a sledgehammer instead of a scalpel but if it helps elsewhere, glad to hear it.

**Comment by kuuji** [comment]
@DavidFW1960 I was planning to do it yesterday but was caught up with a lot of personal stuff. I'm gonna try to make a release today. 

I need to write a small doc for that local dep too

**Comment by gmschade** [comment]
> @DavidFW1960 I was planning to do it yesterday but was caught up with a lot of personal stuff. I'm gonna try to make a release today.
> 
> I need to write a small doc for that local dep too

I just did I little write up for what I did over [here](https://community.home-assistant.io/t/custom-dark-sky-animated-weather-card/59816/571?u=gmschade) if that helps at all.

**Comment by DavidFW1960** [comment]
So the custom-dark-sky weather card here https://github.com/iammexx/home-assistant-config/blob/master/ui/darksky/dark-sky-weather-card.js I hacked it yesterday with the same local-lit fix. But the dev has fixed it so it doesn't need that local lit. @kuuji I'm going to see if I can use that same solution with your card or maybe you might look at that as well??

This is an awesome card.....

**Comment by DavidFW1960** [comment]
My clumsy attempt
```
// #####
// ##### Get the LitElement and HTML classes from an already defined HA Lovelace class
// #####

var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-error-entity-row"));
var html = LitElement.prototype.html;

// #####
// ##### Custom Card Definition begins
// #####

class ButtonCard extends LitElement {

// #####
// ##### Assign the external hass object to an internal class var
// #####

  set Hass(hass) { this._hass = hass }

// #####
// ##### Define Render Template
// #####

  render() {
    const state = hass.states[config.entity];
    switch (config.color_type) {
      case 'blank-card':
        return this.blankCardColoredHtml(state, config);
      case 'label-card':
        return this.labelCardColoredHtml(state, config);
      case 'card':
        return this.cardColoredHtml(state, config);
      case 'icon':
      default:
        return this.iconColoredHtml(state, config);
    }
  }


  getFontColorBasedOnBackgroundColor(backgroundColor) {
    const parsedRgbColor= backgroundColor.match(/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i);
    const parsedBackgroundColor = parsedRgbColor ? parsedRgbColor : this.hexToRgb(backgroundColor.substring(1));
    let fontColor = ''; // don't override by default
    if (parsedBackgroundColor) {
      // Counting the perceptive luminance - human eye favors green color...
      const luminance = (0.299 * parsedBackgroundColor[1] + 0.587 * parsedBackgroundColor[2] + 0.114 * parsedBackgroundColor[3]) / 255;
      if (luminance > 0.5) {
        fontColor = 'rgb(62, 62, 62)'; // bright colors - black font
      } else {
        fontColor = 'rgb(234, 234, 234)';// dark colors - white font
      }
    }
    return fontColor;
  }

  hexToRgb(hex) {
    var bigint = parseInt(hex, 16);
    var r = (bigint >> 16) & 255;
    var g = (bigint >> 8) & 255;
    var b = bigint & 255;

    return [,r,g,b];
  }


  buildCssColorAttribute(state, config) {
    let color = config.color;
    if (state) {
      let configState = config.state ? config.state.find(configState => { return configState.value === state.state; }) : false;
      if(configState){
        color = configState.color ? configState.color : config.color_off;
        if (configState.color === 'auto') {
          color = state.attributes.rgb_color ? `rgb(${state.attributes.rgb_color.join(',')})` : configState.default_color;
        }
      }else{
        if (config.color === 'auto') {
          color = state.attributes.rgb_color ? `rgb(${state.attributes.rgb_color.join(',')})` : config.default_color;
        }
        color = state.state === 'on' ? color : config.color_off;
      }
    }
    return color;
  }

  buildIcon(state, config) {
    let iconOff = config.icon;
    if (config.icon == 'attribute') {
      if (state) {
        const icon = state.attributes.icon;
        return icon;
      }
      return iconOff;
    }
    let configState = config.state ? config.state.find(configState => { return configState.value === state.state; }) : false;
    if (configState && configState.icon) {
      const icon = configState.icon;
      return icon;
    }
    return iconOff;
  }

  blankCardColoredHtml(state, config) {
    const color = this.buildCssColorAttribute(state, config);
    const fontColor = this.getFontColorBasedOnBackgroundColor(color);
    return html`
    <ha-card style="color: ${fontColor}; background-color: ${color}; ${config.card_style}" on-tap="${ev => this._toggle(state, config)}">
    </ha-card>
    `;
  }

  labelCardColoredHtml(state, config) {
    const color = this.buildCssColorAttribute(state, config);
    const fontColor = this.getFontColorBasedOnBackgroundColor(color);
    return html`
    <style>
    ha-icon {
      display: flex;
      margin: auto;
    }
    paper-button {
      display: flex;
      margin: auto;
      text-align: center;
    }
    </style>
    <ha-card style="color: ${fontColor};">
      <paper-button noink style="background-color: ${color}; ${config.card_style}">
      <div>
        ${config.icon ? html`<ha-icon style="width: ${config.size}; height: ${config.size};" icon="${config.icon}"></ha-icon>` : ''}
        ${config.name ? html`<span>${config.name}</span>` : ''}
       </div>
      </paper-button>
    </ha-card>
    `;
  }

  cardColoredHtml(state, config) {
    const color = this.buildCssColorAttribute(state, config);
    const fontColor = this.getFontColorBasedOnBackgroundColor(color);
    return html`
    <style>
    ha-icon {
      display: flex;
      margin: auto;
    }
    paper-button {
      display: flex;
      margin: auto;
      text-align: center;
    }
    </style>
    <ha-card style="color: ${fontColor};" on-tap="${ev => this._toggle(state, config)}">
      <paper-button style="background-color: ${color}; ${config.card_style}">
      <div>
        ${config.icon ? html`<ha-icon style="width: ${config.size}; height: ${config.size};" icon="${config.icon}"></ha-icon>` : ''}
        ${config.name ? html`<span>${config.name}</span>` : ''}
        ${config.show_state ? html`<span>${state.state} ${state.attributes.unit_of_measurement ? state.attributes.unit_of_measurement : ''}</span>` : ''}
       </div>
      </paper-button>
    </ha-card>
    `;
  }

  iconColoredHtml(state, config) {
    const color = this.buildCssColorAttribute(state, config);
    const icon = this.buildIcon(state, config);
    return html`
    <style>
    ha-icon {
      display: flex;
      margin: auto;
    }
    paper-button {
      display: flex;
      margin: auto;
      text-align: center;
    }
    </style>
    <ha-card on-tap="${ev => this._toggle(state, config)}">
      <paper-button style="${config.card_style}">
      <div>
        ${config.icon ? html`<ha-icon style="color: ${color}; width: ${config.size}; height: ${config.size};" icon="${icon}"></ha-icon>` : ''}
        ${config.name ? html`<div>${config.name}</div>` : ''}
        ${config.show_state ? html`<div>${state.state} ${state.attributes.unit_of_measurement ? state.attributes.unit_of_measurement : ''}</div>` : ''}
      </div>
      </paper-button>
    </ha-card>
    `;
  }

  setConfig(config) {
    // if (!config.entity) {
    //   throw new Error('You need to define entity');
    // }
    this.config = {...config};
    this.config.color = config.color ? config.color : 'var(--primary-text-color)';
    this.config.size = config.size ? config.size : '40%';
    let cardStyle = '';
    if (config.style) {
      config.style.forEach((cssObject) => {
        const attribute = Object.keys(cssObject)[0];
        const value = cssObject[attribute];
        cardStyle += `${attribute}: ${value};\n`;
      });
    }
    this.config.color_type = config.color_type ? config.color_type : 'icon';
    this.config.color_off = config.color_off ? config.color_off : 'var(--disabled-text-color)';
    this.config.default_color = config.default_color ? config.default_color : 'var(--primary-text-color)';
    this.config.card_style = cardStyle;
    this.config.name = config.name ? config.name : '';
  }

  // The height of your card. Home Assistant uses this to automatically
  // distribute all cards over the available columns.
  getCardSize() {
    return 3;
  }

  _toggle(state, config) {
    switch (config.action) {
      case 'toggle':
        this._hass.callService('homeassistant', 'toggle', {
          entity_id: state.entity_id,
        });
        break;
      case 'more_info': {
        const node = this.shadowRoot;
        const options = {};
        const detail = { entityId: state.entity_id };
        const event = new Event('hass-more-info', {
          bubbles: options.bubbles === undefined ? true : options.bubbles,
          cancelable: Boolean(options.cancelable),
          composed: options.composed === undefined ? true : options.composed,
        });
        event.detail = detail;
        node.dispatchEvent(event);
        return event;
      }
      case 'service':
        this._hass.callService(config.service.domain, config.service.action, config.service.data);
        break;
      default:
        this._hass.callService('homeassistant', 'toggle', {
          entity_id: state.entity_id,
        });
        break;
    }
  }
}

// #####
// ##### Assign the external hass object to an internal class var.
// ##### This is called everytime a state value changes
// #####

  set hass(hass) { this._hass = hass }


// #####
// ##### Assigng the configuration values to an internal call var
// ##### This is called everytime a config change is made
// #####

  setConfig(config) { this.config = config; }


// #####
// ##### Sets the card size so HA knows how to put in columns
// #####

  getCardSize() { return 3 }
  
}

// ##### 
// ##### Register the card as a customElement
// #####

customElements.define('button-card', ButtonCard);
```

I gt a red button card - doesn't work but maybe it's a simple mistake. @bramkragten maybe you can help?

**Comment by kuuji** [comment]
That's awesome @DavidFW1960 . Let me look into that deeper this week-end. Maybe we don't even need to download lit-element. I like that solution a lot.

I'll try to get that working and released over the weekend. And maybe the long-press action as well.

**Comment by jonostanck** [comment]
If you are planning on adding long_press maybe consider also adding another CASE for using two sets of services - one for action and one for long_press_action. :)

**Comment by kuuji** [comment]
Yeah @jonostanck that's what I had in mind. I'll likely do something similar to what's in the core project.

**Comment by DavidFW1960** [comment]
> That's awesome @DavidFW1960 . Let me look into that deeper this week-end. Maybe we don't even need to download lit-element. I like that solution a lot.
> 
> I'll try to get that working and released over the weekend. And maybe the long-press action as well.

Sounds like the best solution... I just hacked bits from the dark-sky card I referenced above but I've missed something cos it doesn't work... I look forward to your genius!

Thanks again for this great card.

**Comment by bramkragten** [comment]
@DavidFW1960 would love to help, but can't see clearly what you have changed. If you would make a PR I can check it.

**Comment by DavidFW1960** [comment]
> @DavidFW1960 would love to help, but can't see clearly what you have changed. If you would make a PR I can check it.

I didn't want to do a PR because there were still unmerged PR's (like your original fix) and what I have done could be totally wrong.

I was trying to emulate https://github.com/iammexx/home-assistant-config/blob/master/ui/darksky/dark-sky-weather-card.js dark-sky-weather card which he modified to get the LitElement and HTML classes from an already defined HA Lovelace class rather than from the internet that caused so many problems over the last few days. But really I have no actual idea what I am doing so I just posted the total js code in my post above...

**Comment by bramkragten** [comment]
Yeah that should work, if this element works with the version of Lit home Assistant ships with...

**Comment by kuuji** [comment]
I just released a version without the remote dependency folks. 

I'v had to fix a few things to get it to work but it's should be all good now.

**Comment by soberstadt** [comment]
I also updated to 23bc58cda2ea2022e09ec278c906f9c0d25cafdb and it's working again. Yay!

**Comment by IIIdefconIII** [comment]
Thanks kuuji for maintaining one of the best cards

**Comment by septeven** [comment]
Please reopen.
I still have this problem. I tried to clear the cache, add version to "/local/button-card.js?v=0.0.8", etc.. nothing : I still have the red card. (Hassio 0.85.1)
It only occurs in Safari 11.0.3 (MacOS 10.13.3) though, chrome, safari on ios, etc... are all fine.

Debug tools are displaying these error as well: 
"Unhandled Promise Rejection: /local/button-card.js"
"[Error] SyntaxError: Unexpected token '...'. Expected a property name."
"Failed to set referrer policy: The value 'same-origin' is not one of 'no-referrer', 'origin', 'no-referrer-when-downgrade', or 'unsafe-url'. Defaulting to 'no-referrer'."

Please note I am pretty new with Hassio.
Thanks

**Comment by jonostanck** [comment]
@septeven [Here](https://github.com/kuuji/button-card/pull/45#issuecomment-456107477) is the remedy for your problem.

**Comment by septeven** [comment]
@jonostanck Thanks, but what should I do with it ?

**Comment by jonostanck** [comment]
@septeven Change in button-card.js:
`{...config}` to `Object.assign({}, config)`

**Comment by septeven** [comment]
@jonostanck Thanks. It worked perfectly. One question though : Why should I have to edit this since from what I understand, my Safari (11.0.3) should support spread syntax ?

**Comment by jonostanck** [comment]
@septeven Well I guess it's not - full support (Spread in object literals) starts from 11.1.
